import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components";

const fontFamily = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontFamily.className} text-white mx-auto z-10`}
      >
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <div className="spark fixed z-20"></div>
        <Navbar />
        <main className="min-h-screen bg-background">{children}</main>
      </body>
    </html>
  );
}
